#!/bin/bash

# bash_config

# Make vim the default editor
export EDITOR="nano"

# Ignore duplicate commands in the history
export HISTCONTROL=ignoredups

# Increase the maximum number of lines contained in the history file
# (default is 500)
export HISTFILESIZE=10000

# Increase the maximum number of commands to remember
# (default is 500)
export HISTSIZE=10000

# Make some commands not show up in history
export HISTIGNORE="ls:ls *:cd:cd -:pwd;exit:date:* --help"

# Don't clear the screen after quitting a manual page
export MANPAGER="less -X"

# Make new shells get the history lines from all previous
# shells instead of the default "last window closed" history
export PROMPT_COMMAND="history -a; $PROMPT_COMMAND"

# NPM path
export PATH="/usr/local/share/npm/bin:${PATH}"

# Link RVM
[[ -s "$HOME/.rvm/scripts/rvm" ]] && . "$HOME/.rvm/scripts/rvm"

# Fix Homebrew path
homebrew=/usr/local/bin:/usr/local/sbin
export PATH="$homebrew:$PATH"

# Local bin path
export PATH="$PATH:~/bin"

# Go exports
export GOVERSION="1.1.2"
export GOROOT=$(brew --prefix)/Cellar/go/$GOVERSION
export GOPATH=$(brew --prefix)/Cellar/go/$GOVERSION/bin
export PATH=$PATH:$GOPATH/bin

# Rails development
export DEVELOPER="josh"
PATH="$PATH:$HOME/.rvm/bin" # Add RVM to PATH for scripting

# MySQL
MYSQL=/usr/local/mysql/bin
export PATH="$PATH:$MYSQL"
export DYLD_LIBRARY_PATH="/usr/local/mysql/lib:$DYLD_LIBRARY_PATH"